pub const DEFAULT_LOCAL_TCP_PORT: u16 = 44322;
pub const DEFAULT_LOCAL_UDP_PORT: u16 = 53445;
pub const DEFAULT_HOP_LIMIT: u8 = 64;
pub const DEFAULT_HOSTS_CONCURRENCY: usize = 50;
pub const DEFAULT_PORTS_CONCURRENCY: usize = 100;
pub const PCAP_WAIT_TIME_MILLIS: u64 = 10;
